Repository einn-software/Campus_Recruitment_App, pull requests merged in 2020-07, with the labels that each got.

#143 [Task/CRA- 141] Final submission bug fixed
  backend/controller/errorHandling.js
  backend/controller/examinationController.js
  backend/controller/instructionController.js
  backend/controller/resultController.js
Labels: solved

#150 [Task/cra 144] Tpo and student data update after college update
  backend/config/validation.js
  backend/controller/collegeRouteController.js
Labels: solved

#159 "Crash on Result Fixed"
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/examination/ExamDrawer.kt
Labels: bug

#162 [Task/CRA]-153: Integrate Crashlytics and Google Analytics with app
  android/MaterialDesignTest/app/build.gradle
  android/MaterialDesignTest/app/google-services.json
  android/MaterialDesignTest/build.gradle
Labels: enhancement

#170 [Task/CRA-167] Changes in upload logs and files API and selected option in validation file
  backend/config/validation.js
  backend/controller/uploadAndRegisterStudent.js
Labels: solved

#176 [Task/cra 174] - #174 issue - Upload API bug solved
  backend/controller/uploadAndRegisterStudent.js
Labels: solved

#178 [Task/CRA-166]: Android: Create Logfile and send logs to server
  android/MaterialDesignTest/app/build.gradle
  android/MaterialDesignTest/app/src/main/AndroidManifest.xml
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/data/interactor/implementation/CollegeDetails.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/data/interactor/implementation/ExaminationRepo.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/data/interactor/implementation/PreExamInstructionsRepo.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/data/interactor/implementation/QuestionPaperRepo.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/data/interactor/implementation/ResultRepo.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/data/interactor/implementation/UserRepository.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/data/network/repository/CollegeDetailsRemoteRepo.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/data/network/repository/ExaminationRemoteRepo.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/data/network/repository/PreExamInstructionsRemoteRepo.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/data/network/repository/QuestionPaperRemoteRepo.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/data/network/repository/ResultRemoteRepo.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/data/network/repository/UserRemoteRepository.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/data/session/SessionManager.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/examination/ExamDrawer.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/examination/ExamSectionFragment.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/examination/ExaminationPresenter.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/examination/ExaminationSectionPresenter.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/instructions/ExamInfo.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/instructions/ExamInfoPresenter.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/instructions/InstructionActivity.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/instructions/InstructionPresenter.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/instructions/InstructionsFragment.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/login/LoginActivity.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/login/LoginPresenter.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/login/LoginPrompt.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/login/StudentLogin.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/login/TpoLoginActivity.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/login/TpoLoginPresenter.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/resetAuthentication/ResetAuthenticationActivity.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/resetAuthentication/ResetAuthenticationPresenter.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/result/ResultActivity.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/result/ResultsFragment.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/result/ResultsPresenter.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/splash/SplashActivity.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/tpoDashboard/CollegeDeatilsFragment.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/tpoDashboard/CollegeDetailsPresenter.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/tpoDashboard/DataUpload.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/tpoDashboard/DataUploadPresenter.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/tpoDashboard/QuestionPaperListFragment.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/tpoDashboard/QuestionPaperListPresenter.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/tpoDashboard/ResultListFragment.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/tpoDashboard/ResultListPresenter.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/tpoDashboard/TPODashboardPresenter.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/ui/tpoDashboard/TpoDashboard.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/utils/Constants.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/utils/CustomLogMessageFormat.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/utils/Logger.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/utils/callListner/CallReceiver.kt
  android/MaterialDesignTest/app/src/main/java/com/testexample/materialdesigntest/utils/callListner/MyPhoneStateListener.kt
Labels: enhancement

#177 [Task/cra 165] - Error message improvement
  backend/config/markscalculation.js
  backend/controller/collegeRouteController.js
  backend/controller/errorHandling.js
  backend/controller/examinationController.js
  backend/controller/getPutDeleteController.js
  backend/controller/instructionController.js
  backend/controller/registerController.js
  backend/controller/resultController.js
  backend/controller/studentAnswerSheet.js
  backend/controller/uploadAndRegisterStudent.js
Labels: solved

#180 [Task/cra 148 recreate] - Add Logging and logs file rotator
  backend/.gitignore
  backend/config/constant.js
  backend/config/logger.js
  backend/config/markscalculation.js
  backend/config/rotateLogAndDeleteOldLogFiles.js
  backend/config/verifyToken.js
  backend/controller/changePasswordController.js
  backend/controller/collegeRouteController.js
  backend/controller/examinationController.js
  backend/controller/finalSubmission.js
  backend/controller/getPutDeleteController.js
  backend/controller/instructionController.js
  backend/controller/loginController.js
  backend/controller/registerController.js
  backend/controller/resultController.js
  backend/controller/studentAnswerSheet.js
  backend/controller/uploadAndRegisterStudent.js
  backend/crs.js
  backend/index.js
  backend/package.json
Labels: solved

#184 [Task/CRA-181]
  backend/controller/changePasswordController.js
Labels: solved

#185 [Task/CRA-182]
  backend/config/markscalculation.js
Labels: solved
